- hosts: pulsarservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: system update
      ansible.builtin.dnf:
        name: '*'
        state: latest
    - name: Install Pulsar dependencies
      become: yes
      ansible.builtin.dnf:
        state: latest
        name:
          - git
          - python36
          - python38
          - python3-devel
          - python3-virtualenv
          - gcc
          - curl
          - libcurl-devel
          - openssl-devel
    - name: Set default version of Python
      ansible.builtin.alternatives:
        name: python
        path: /usr/bin/python3
    - name: Disable SELinux.
      ansible.posix.selinux:
        state: disabled
  roles:
    - galaxyproject.cvmfs
    - galaxyproject.pulsar
  post_tasks:
    - name: Disable firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: no
        state: stopped
