- hosts: pulsarservers
  pre_tasks:
    - name: Install some packages
      package:
        name: ['gcc-toolset-11-toolchain', 'git', 'python3', 'curl', 'libcurl-devel', 'openssl-devel', 'virtualenv']
        state: present
        update_cache: yes
      become: yes
  roles:
    - role: galaxyproject.cvmfs
      become: yes
    - galaxyproject.pulsar
